### ISSUE TITLE
Browser borders shouldn't appear in screenshots and shouldn't be used in the `resize` calculation 

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-browser-natives#57]
Currently `resize` works incorrectly - it resizes the whole browser window to the given size, not only client area. Guys, from DevExtreme figured out how to avoid it. We can use their algorithm to remove browser UI from the screenshots. Please, contact Konstantin Volnyagin for details.

\cc @AlexanderMoskovkin @AndreyBelym

**Comment by AndreyBelym** [comment]
I'm working on it.
