### ISSUE TITLE
The 'write EIO' error appeared when console trying to write unicode symbols after getInstallations() method call.

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-browser-natives#58]
At this moment API method getInstallations() changes codepage during his execution.
[findWindowsBrowsers() method](https://github.com/DevExpress/testcafe-browser-natives/blob/master/src/api/get-installations.js#L44)
[detectMicrosoftEdge() method](https://github.com/DevExpress/testcafe-browser-natives/blob/master/src/api/get-installations.js#L32)
If terminal's default codepage is different from 65001 (437 in our case), it's going to crash TestCafe when trying to display unicode symbols after this change.
To check default codepage run in command line:
``` cmd
chcp
```

**Comment by AlexanderMoskovkin** [comment]
We need this [code page changing](https://github.com/DevExpress/testcafe-browser-natives/blob/master/src/api/get-installations.js#L44) for the `reg query` command in the windows with Russian (also maybe Chienese, etc) localization. A possible solution - store current code page before this executing and restore it then

**Comment by georgiy-abbasov** [comment]
FPR
