### ISSUE TITLE
Simplify search of IE windows

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-natives#64]
IE creates a main browser window, and a preview windows for each tab. So IE have two windows with same title. Currently the way that we use to distinguish main window from preview window, is quite complex, and it requires to specify URL of the page that is inside the window.

We can easily filter preview windows by checking their [class names](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms633582(v=vs.85).aspx): preview windows have `TabThumbnailWindow` as a class name, main window has `IEFrame`.

**Comment by AlexanderMoskovkin** [comment]
have you checked does it work in Win7,8,10 ?

**Comment by AndreyBelym** [comment]
It works Win7 + IE9, Win10 + IE11. I need volunteers for testing on Win8, or a VM.
