### ISSUE TITLE
Executable permission flag on 'bin/mac/screenshot' is lost when publishing module on Windows

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-natives#78]
Screenshots are not working on OS X, because we are publishing module on Windows, and `x` flag (UNIX executable file permission flag) is not saved on binary `bin/mac/screenshot` in package tarball. So the binary can not be executed after module installation.

**Comment by inikulin** [comment]
@AndreyBelym can we set executable flag as postinstall action?

**Comment by AndreyBelym** [comment]
yep, I'll send a PR.
