### ISSUE TITLE
False-positive detecting of Microsoft Edge

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-natives#85]
It's happening because `cmd.exe` prints the command to `stdout` before it will be executed, so `/SUCCESS/.test(stdout)` is always true, because the command contains `&& echo SUCCESS || echo FAIL`. See [here](https://github.com/DevExpress/testcafe-browser-natives/blob/master/src/api/get-installations.js#L32).

**Comment by inikulin** [comment]
Yeah, reproduced on my Windows 8.1 machine. I don't have Edge here, but it's detected
