### ISSUE TITLE
Rename the package to avoid reference to testcafe

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-natives#95]
\cc @inikulin @AlexanderMoskovkin @VasilyStrelyaev @MargaritaLoseva 
We need to choose a new name for the package, to state that is a library independent from `testcafe` for managing browser processes and windows.

**Comment by inikulin** [comment]
`testcafe-browser-utils`. It's utility library that can be used by browser provider plugins
